### ISSUE TITLE
Implement Linting and Testing frameworks

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#33]
**Feature Name**
Dev Linting and Testing tools

**Description**
Integrating linting and testing tools allow developers to ensure their code is neat and functional

**Requires**
- React, Webpack, and Babel to be implemented

**Subtask Breakdown**
- [ ] Determine testing framework
- [ ] Implement testing framework
- [x] Implement ESLint
- [x] Set up ESLint rules

**Due**
Milestone 2

**Time Estimation:**
6hrs.

**Comment by bndnio** [comment]
Finished Linter and rules, need to tackle testing now

**Comment by hwkr** [comment]
@BrendonEarl how does the linter run?

**Comment by bndnio** [comment]
ESlint collects the rules in .eslint.js and runs through them in the webpack build process (as a pre-loader)

**Comment by hwkr** [comment]
Okay, it doesn't seem to be linting .jsx files

**Comment by hwkr** [comment]
Can we set up pre commit linting? I think [this might work](https://gist.github.com/wesbos/8aec9d2ff7f7cf9dd65ca2c20d5dfc23).

**Comment by bndnio** [comment]
Looks like it, only thing is whether that'll prevent a commit if any error or warning occurs or only if an error occurs

**Comment by hwkr** [comment]
I think we should prevent commits with warnings too.
Side note: you should fix the warnings in the samples or update the linting spec.

**Comment by hwkr** [comment]
Tests are lame. Lolz.
