### ISSUE TITLE
Add font and style loaders

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#34]
**Feature Name**
Add web pack font and style (less/css) loaders

**Description**
Adding font and style loaders allow developers to inject styles into the product

**Requires**
- React, Webpack, and Babel must be implemented

**Subtask Breakdown**
- [x] Implement style loaders
- [x] Implement font loaders
- [x] Identify and add any missing loaders

**Due**
Milestone 2

**Time Estimation:**
2 hrs.

**Comment by bndnio** [comment]
Finished, took ~1 hr
